FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirements/train.txt /app/requirements/train.txt

RUN python -m venv /opt/venv \
    && /opt/venv/bin/pip install --no-cache-dir \
    -r /app/requirements/train.txt


FROM python:3.11-slim AS training

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1

COPY src/ /app/src/
COPY configs/ /app/configs/

ENTRYPOINT ["python", "src/train.py"]